### ISSUE TITLE
Failed to build SAM-2 and RuntimeError in infer

### ISSUE THREAD

**Issue by flashingtt** [facebookresearch/segment-anything-2#18]
When I run the command
```shell
pip install -e .
```
There is an error: 
```shell
RuntimeError:
The detected CUDA version (11.8) mismatches the version that was used to compile
PyTorch (12.1). Please make sure to use the same CUDA versions.
```

I try to use the command below to fix this error:
```shell
pip install --no-build-isolation -e .
```

Although I build SAM-2 successfully, there is another error when I run the inference image segmentation script:
```shell
RuntimeError: GET was unable to find an engine to execute this computation
```

Does anyone have the same problem?

**Comment by HB16888** [comment]
I have the same problem
RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.

**Comment by Kiran-valetcloset** [comment]
I too have the same problem. I have installed the cuda toolkit 11.8, checked it from nvcc -V command and installed pytorch using 11.8 cuda too, but I still get the same error.

**Comment by laiwenq** [comment]
You can upgrade your cuda to 12.1. Otherwise manually install the dependencies, e.g., pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

**Comment by flashingtt** [comment]
> You can upgrade your cuda to 12.1. Otherwise manually install the dependencies, e.g., pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

@laiwenq Thank you for your reply. I have tried
```shell
pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
pip install --no-build-isolation -e .
```
Then I build SAM2 successfully, but failed to infer. 
Is it a problem with the cuda version? My current version is 11.8, and I will upgrade to 12.1 later and try again.

**Comment by fangli333** [comment]
> > You can upgrade your cuda to 12.1. Otherwise manually install the dependencies, e.g., pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
> 
> @laiwenq Thank you for your reply. I have tried
> 
> ```shell
> pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
> pip install --no-build-isolation -e .
> ```
> 
> Then I build SAM2 successfully, but failed to infer. Is it a problem with the cuda version? My current version is 11.8, and I will upgrade to 12.1 later and try again.

did you solve it?

**Comment by laiwenq** [comment]
> > You can upgrade your cuda to 12.1. Otherwise manually install the dependencies, e.g., pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
> 
> @laiwenq Thank you for your reply. I have tried
> 
> ```shell
> pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
> pip install --no-build-isolation -e .
> ```
> 
> Then I build SAM2 successfully, but failed to infer. Is it a problem with the cuda version? My current version is 11.8, and I will upgrade to 12.1 later and try again.

Can you post what error you're seeing? I have no problem with torch==2.3.1 and cuda version 12.1, it is worth trying upgrade your cuda.

**Comment by flashingtt** [comment]
@laiwenq @fangli333 @HB16888 @Kiran-valetcloset @ChinaStark 
After I upgraded my cuda to 12.1, all problems were solved. I can follow the official step-by-step installation smoothly.
Thanks to @laiwenq 's help.

**Comment by proxi666** [comment]
perhaps, we need cuda 12+ for it to run?

**Comment by majnas** [comment]
```
            .-/+oossssoo+/-.               dev@av1 
        `:+ssssssssssssssssss+:`           ------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 23.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: GE76 Raider 11UH REV:1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.5.0-44-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 15 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3012 (dpkg), 23 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.9 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 2048x1152, 1920x1080, 2560x1440 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 45.2 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-viridian [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-viridian [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: 11th Gen Intel i9-11980HK (16) @ 4.900GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce RTX 3080 Mobile / Max-Q 8GB/16GB 
      -+sssssssssssssssssyyyssss+-         GPU: Intel TigerLake-H GT1 [UHD Graphics] 
        `:+ssssssssssssssssss+:`           Memory: 3764MiB / 31787MiB 
            .-/+oossssoo+/-.
                                                                   
                                                                   
```
I have tested gcc-9/10/11 none of them worked. finally upgrade cuda toolkit to 12.1 solved the problem
```
wget https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda_12.1.0_530.30.02_linux.run
sudo sh cuda_12.1.0_530.30.02_linux.run --toolkit --toolkitpath=/usr/local/cuda-12.1 --override
```

**Comment by YichiZhang98** [comment]
> You can upgrade your cuda to 12.1. Otherwise manually install the dependencies, e.g., pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118

Thank you for your reply. I have tried but failed to build.

The error shows as follows.


  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for SAM-2
Failed to build SAM-2
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (SAM-2)

My cuda version 12.1 bu it still not work.

**Comment by Yan-0-0-Ye** [comment]
> > 您可以将 cuda 升级到 12.1。否则手动安装依赖项，例如，pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
> 
> 感谢您的回复。我试过但未能构建。
> 
> 错误如下所示。
> 
> 注意：此错误源自子进程，可能不是 pip 的问题。错误：无法为 SAM-2 构建可编辑内容 无法生成 SAM-2 错误：错误：无法为某些基于 pyproject.toml 的项目 （SAM-2） 构建可安装轮子
> 
> 我的 cuda 版本 12.1 bu 它仍然不起作用。

hello, do you solve it?

**Comment by laiwenq** [comment]
> > You can upgrade your cuda to 12.1. Otherwise manually install the dependencies, e.g., pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
> 
> Thank you for your reply. I have tried but failed to build.
> 
> The error shows as follows.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building editable for SAM-2 Failed to build SAM-2 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (SAM-2)
> 
> My cuda version 12.1 bu it still not work.

Sorry just see this now. Check your cuda version by running nvcc -V in the command line and see if you are actually using 12.1.

**Comment by Yan-0-0-Ye** [comment]
> > > You can upgrade your cuda to 12.1. Otherwise manually install the dependencies, e.g., pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
> > 
> > 
> > Thank you for your reply. I have tried but failed to build.
> > The error shows as follows.
> > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building editable for SAM-2 Failed to build SAM-2 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (SAM-2)
> > My cuda version 12.1 bu it still not work.
> 
> Sorry just see this now. Check your cuda version by running nvcc -V in the command line and see if you are actually using 12.1.

thanks!

**Comment by ronghanghu** [comment]
Hi, we have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155) as a workaround to this problem.

You can pull the latest code and reinstall via
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
pip install -e ".[demo]"
```
which allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).

**Comment by zhirui-gao** [comment]
> > You can upgrade your cuda to 12.1. Otherwise manually install the dependencies, e.g., pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
> 
> Thank you for your reply. I have tried but failed to build.
> 
> The error shows as follows.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building editable for SAM-2 Failed to build SAM-2 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (SAM-2)
> 
> My cuda version 12.1 bu it still not work.

I find restart the ubuntu can fix that problem.  After upgrading the cuda to 12.1, I still  can't run the inference code, although the nvcc shows the cuda is 12.1. But I restat my computer, it runs smoothly.

**Comment by fangzhou2000** [comment]
To use cuda 11.8, try to install torch with cuda 11.8 and other dependencies first, then run pip install -e . --no-build-isolation --no-deps
